version: '3.9'
services:
  database:
    container_name: ewallet
    image: postgres:15.2
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes: 
       - postgres-db:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - network1
    restart: always 

  adminer: 
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - network1

  backend:
    container_name: backend
    build: ./
    depends_on:
      - database
    ports:
      - "8000:8000"
    networks:
      - network1
    restart: always
       
volumes:
  postgres-db:
    driver: local

networks:
  network1:
    name: network1